### ISSUE TITLE
The mod can not work now.

### ISSUE THREAD

**Issue by RDCJ** [MDModsDev/QuickSwitchCombination#1]
The error message: 
[17:11:27.874] [QuickSwitchCombination] QuickSwitchCombination is loaded!
Setting breakpad minidump AppID = 774171
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198232132616 [API loaded no]
[17:11:55.245] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppNewtonsoft.Json.Linq.JArray Il2CppAssets.Scripts.PeroTools.Managers.ConfigManager.get_Item(System.String)'.
   at QuickSwitchCombination.Character.Start()
   at Trampoline_VoidThisQuickSwitchCombination.CharacterStart(IntPtr , Il2CppMethodInfo* )
[17:11:55.245] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppNewtonsoft.Json.Linq.JArray Il2CppAssets.Scripts.PeroTools.Managers.ConfigManager.get_Item(System.String)'.
   at QuickSwitchCombination.Elfin.Start()
   at Trampoline_VoidThisQuickSwitchCombination.ElfinStart(IntPtr , Il2CppMethodInfo* )

**Comment by lxymahatma** [comment]
> The error message: [17:11:27.874] [QuickSwitchCombination] QuickSwitchCombination is loaded! Setting breakpad minidump AppID = 774171 SteamInternal_SetMinidumpSteamID: Caching Steam ID: 76561198232132616 [API loaded no] [17:11:55.245] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppNewtonsoft.Json.Linq.JArray Il2CppAssets.Scripts.PeroTools.Managers.ConfigManager.get_Item(System.String)'. at QuickSwitchCombination.Character.Start() at Trampoline_VoidThisQuickSwitchCombination.CharacterStart(IntPtr , Il2CppMethodInfo* ) [17:11:55.245] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: System.MissingMethodException: Method not found: 'Il2CppNewtonsoft.Json.Linq.JArray Il2CppAssets.Scripts.PeroTools.Managers.ConfigManager.get_Item(System.String)'. at QuickSwitchCombination.Elfin.Start() at Trampoline_VoidThisQuickSwitchCombination.ElfinStart(IntPtr , Il2CppMethodInfo* )

Because currently I'm busy with other stuff, this mod is no longer maintained 😔
I think it's when opening the menu to set combinations right?
maybe the only way now is to write them manually, i can give u my .cfg file here as reference

```toml
# Menu for adding settings
MenuKey = "F11"

[[Data]]
# The character index
Character = 11
# The elfin index
Elfin = 7
# The shortcut key for switching character
Key = "Alpha1"

[[Data]]
# The character index
Character = 3
# The elfin index
Elfin = 5
# The shortcut key for switching character
Key = "Alpha2"

[[Data]]
# The character index
Character = 3
# The elfin index
Elfin = 6
# The shortcut key for switching character
Key = "Alpha3"

[[Data]]
# The character index
Character = 7
# The elfin index
Elfin = 5
# The shortcut key for switching character
Key = "Alpha4"

[[Data]]
# The character index
Character = 7
# The elfin index
Elfin = 6
# The shortcut key for switching character
Key = "Alpha5"

[[Data]]
# The character index
Character = 2
# The elfin index
Elfin = -1
# The shortcut key for switching character
Key = "Alpha6"
```
